name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Snake Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install xvfb and sound dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libasound2-dev python3-tk python3-dev

      - name: Run Snake Game (Headless Mode)
        run: |
          # Start Xvfb with more verbose logging
          Xvfb :99 -screen 0 1280x1024x24 -ac -nolisten tcp &
          XPID=$!
          export DISPLAY=:99
          export SDL_AUDIODRIVER=dummy
          
          # Debug: Check Xvfb is running
          ps -p $XPID >/dev/null && echo "Xvfb running (PID $XPID)" || echo "Xvfb failed to start"
          
          # Run game with timeout and debug output
          echo "Starting snake game..."
          set -x  # Enable debug output
          python -v snake.py &
          GPID=$!
          
          # Wait for maximum 20 seconds
          for i in {1..20}; do
            if ! ps -p $GPID >/dev/null; then
              echo "Game exited normally"
              break
            fi
            sleep 1
            echo "Waiting... ($i seconds elapsed)"
          done
          
          # Cleanup
          kill -9 $GPID 2>/dev/null || true
          kill -9 $XPID 2>/dev/null || true
          echo "Test completed"

  deploy:
    name: Deploy to GCP
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Enable Required APIs
        run: |
          gcloud services enable cloudresourcemanager.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud services enable cloudbuild.googleapis.com
          gcloud services enable artifactregistry.googleapis.com
          continue-on-error: true  # In case you already enabled them manually

      - name: Deploy to Cloud Run
        run: 
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud builds submit \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/snake-game \
          --timeout=20m
    
         gcloud run deploy snake-game \
         --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/snake-game \
         --platform managed \
         --region us-central1 \
         --allow-unauthenticated \
         --timeout=10m
#----------------------------------------------------------------------------------------------------



# name: Python CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"  # Change if needed

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Install xvfb for headless display
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y xvfb

#       - name: Run Snake Game (Headless Mode)
#         run: |
#           # Start xvfb in the background
#           Xvfb :99 -screen 0 1280x1024x24 &

#           # Set the DISPLAY environment variable for headless mode
#           export DISPLAY=:99

#           # Run the Snake game
#           python snake.py &
          
#           # Give it some time to run
#           sleep 10

#           # Kill the Snake game process
#           pkill -f snake.py

#           # Kill the Xvfb process after the test
#           pkill Xvfb

#       name: Deploy to GCP

# on:
#   push:
#     branches:
#       - main  # Change if using a different branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Set Up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v2

#       - name: Deploy to Cloud Run
#         run: |
#           gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
#           gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/snake-game
#           gcloud run deploy snake-game \
#             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/snake-game \
#             --platform managed \
#             --region us-central1 \
#             --allow-unauthenticated



# name: Python CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"  # Change if needed

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Install xvfb for headless display
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y xvfb

#       - name: Run Snake Game (Headless Mode)
#         run: |
#           # Start xvfb in the background
#           Xvfb :99 -screen 0 1280x1024x24 &

#           # Set the DISPLAY environment variable for headless mode
#           export DISPLAY=:99

#           # Run the Snake game
#           python snake.py &
          
#           # Give it some time to run
#           sleep 10

#           # Kill the Snake game process
#           pkill -f snake.py

#           # Kill the Xvfb process after the test
#           pkill Xvfb

# ---------------------------------------------------------------------------------------------------

# name: Python CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"  # Change if needed

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Snake Game (Headless Mode)
#         run: |
#           python snake.py
#           sleep 10
#           pkill -f snake.py

#   deploy:
#    needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Snake Game (Headless Mode)
#         run: |
#           python snake.py

#       - name: Deploy Application
#         run: echo "Deployment steps go here"

# ---------------------------------------------------------------------------------

# name: Python CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  # Runs when you push to the main branch
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"  # Change if needed

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Snake Game (Headless Mode)
#         run: |
#           python snake.py

  # deploy:
  #   needs: build  # Ensure the build job completes successfully before deploying
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"

  #     - name: Install Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Build Static Files (Optional)
  #       run: |
  #         # If your game generates static files (e.g., HTML, JS), build them here
  #         echo "Building static files..."

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./  # Change this to the directory containing your static files
  #         keep_files: true  # Keep existing files in the gh-pages branch
